spring:
  application:
    name: ecocash

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

ecocash:
  base-url: ${ECOCASH_BASE_URL}
  api:
    key: ${ECOCASH_API_KEY}
  status: ${ECOCASH_SANDBOX}
  callback:
    url: ${ECOCASH_CALLBACK_URL}